spring:
  application:
    name: lms-statistics
  cloud:
    nacos:
      server-addr: localhost:8848
  config:
    import:
      - optional:nacos:lms-common.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:lms-statistics.yaml?group=DEFAULT_GROUP&refreshEnabled=true
